name: Azure IQ Testing with Pester

on:
  push:
    branches:
      - main

jobs:
  run-pester-tests:
    runs-on: windows-latest 

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Azure PowerShell
        run: |
          Install-Module -Name Az -AllowClobber -Force -SkipPublisherCheck

      - name: Log in to Azure using Service Principal
        run: |
          Connect-AzAccount -ServicePrincipal -TenantId ${{ secrets.AZURE_TENANT_ID }} -ApplicationId ${{ secrets.AZURE_CLIENT_ID }} -CertificateThumbprint ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Pester Tests
        run: |
          continue-on-error: true
          Invoke-Pester -Script .\az-tests\azure_pester.ps1
        shell: pwsh

