name: Azure Pester Tests

on:
  push:
    branches:
      - main

jobs:
  pester_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: azure/powershell@v2
        with:
          version: '7.2.9'

      - name: Install Azure PowerShell
        run: |
          Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser

      - name: Connect to Azure
        run: |
          Connect-AzAccount -ServicePrincipal -TenantId ${{ secrets.AZURE_TENANT_ID }} -ApplicationId ${{ secrets.AZURE_CLIENT_ID }}

      - name: Run Pester tests
        run: |
          Install-Module -Name Pester -Force -AllowClobber -Scope CurrentUser
          Invoke-Pester -Script .\az-tests\azure_pester.ps1
