name: Azure IQ Testing with Pester

on:
  push:
    branches:
      - main

jobs:
  run-pester-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Uninstall AzureRM module (if present)
        run: |
          if (Get-Module -ListAvailable -Name AzureRM) {
              Uninstall-Module -Name AzureRM -Force -AllowClobber
          }

      - name: Install Azure PowerShell (Az module)
        run: |
          Install-Module -Name Az.Resources -Force -AllowClobber -SkipPublisherCheck

      - name: Log in to Azure using Service Principal (PowerShell)
        run: |
          $tenantId = "${{ secrets.AZURE_TENANT_ID }}" 
          $clientId = "${{ secrets.AZURE_CLIENT_ID }}"
          $clientSecret = "${{ secrets.AZURE_CLIENT_SECRET }}"

          $secureSecret = ConvertTo-SecureString $clientSecret -AsPlainText -Force
          $credentials = New-Object System.Management.Automation.PSCredential($clientId, $secureSecret)

          # Ensure connection to Azure with Service Principal
          Connect-AzAccount -ServicePrincipal -TenantId $tenantId -ApplicationId $clientId -Credential $credentials

      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Set Azure Subscription and Run Pester Tests
        continue-on-error: true
        run: |
          $subscriptionId = "0b7e0b83-0035-48fe-92fe-bf1143f2e715"
          Set-AzContext -SubscriptionId $subscriptionId
          Invoke-Pester -Script .\az-tests\azure_pester.ps1
        shell: pwsh
