name: Run Pester Tests for Azure Resources

on:
  push:
    branches:
      - main  

jobs:
  run-pester-tests:
    runs-on: windows-latest  

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azure-cli-version: '2.47.0'  

      # Install Azure PowerShell module
      - name: Install Azure PowerShell Module
        run: |
          Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser

      # Set up Azure authentication using Service Principal
      - name: Authenticate to Azure
        run: |
          Connect-AzAccount -ServicePrincipal -TenantId ${{ secrets.AZURE_TENANT_ID }} -ApplicationId ${{ secrets.AZURE_CLIENT_ID }}

      # Install Pester module
      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -AllowClobber -Scope CurrentUser

      # Run the Pester tests and output to XML
      - name: Run Pester Tests
        continue-on-error: true
        run: |
          Invoke-Pester -Path ./az-tests/azure_pester.ps1 -OutputFormat NUnitXml -OutputFile ./test-results/test-results.xml

      # Upload test results to GitHub Actions
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pester-test-results
          path: ./test-results/test-results.xml
