name: Azure IQ Testing with Pester

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pester-tests:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile ./azure-cli-installer.msi
          Start-Process msiexec.exe -ArgumentList '/i', './azure-cli-installer.msi', '/quiet', '/norestart' -NoNewWindow -Wait

      - name: Log in to Azure using Service Principal
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck
      - name: Install Azure PowerShell Az Module
        run: |
          Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser

      - name: Authenticate to Azure
        run: |
          Connect-AzAccount -ServicePrincipal -TenantId ${{ secrets.AZURE_TENANT_ID }} -ApplicationId ${{ secrets.AZURE_CLIENT_ID }}

      - name: Run Pester Tests
        run: |
          # Path to the Pester test scripts
          Invoke-Pester -Script .\az-tests\azure_pester.ps1 -OutputFormat NUnitXml -OutputFile ./test-results/test-results.xml
        shell: pwsh 